[build-system]
requires = ["flit-core >= 3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyomo_cpsat"
version = "0.0.1"
authors = [
  { name = "Nelson Uhan", email = "nelson@uhan.me" }
]
description = "Pyomo interface to CP-SAT"
readme = "README.md"
dependencies = ["pyomo >= 6.5"]
